---
- when: state != 'absent'
  block:
    - name: "Create SecGrp {{ securitygroup_name }}"
      os_security_group:
        state: "{{ state }}"
        name: "{{ securitygroup_name }}"
        description: "{{ description }}"

    - name: Add rule
      os_security_group_rule:
        security_group: "{{ securitygroup_name }}"
        protocol: "{{ item.protocol | default(omit) }}"
        remote_ip_prefix: "{{ item.remote_ip_prefix | default(omit) }}"
        remote_group: "{{ item.remote_group | default(omit) }}"
        port_range_min: "{{ item.port_range_min | default(omit) }}"
        port_range_max: "{{ item.port_range_max | default(omit) }}"
      loop: "{{ rules }}"

- when: state == 'absent'
  block:
    - name: Delete SecGrp
      os_security_group:
        state: "{{ state }}"
        name: "{{ securitygroup_name }}"
